#!/bin/bash

# Change IFS so for loop doesn't break up file names with spaces
PATH=$PATH:/usr/local/bin
IFS=$'\n'

usage()
{
    echo "Usage:";
    echo "  composter DIR [DAYS1] [DAYS2]";
    echo "";
    echo "Description:";
    echo "  Moves files in DIR to DIR/archive if they're older than DAYS1. Delete all files older than DAYS2";
    echo "    DAYS1 Default: 7";
    echo "    DAYS2 Default: 30";
    echo "";
}

grepExec='grep'
findExec='find'

if [[ `uname` == 'Darwin' ]]; then
    grepExec='ggrep'
    findExec='gfind'
fi

DAYS1=7;
DAYS2=30;

if [[ $# -lt 1 ]]; then
    echo "Must specify a directory!"
    usage
    exit
fi

if [[ $# -ge 1 ]]; then
    DIR="$1/"
fi

if [[ $# -ge 2 ]]; then
    DAYS1=$2
fi

if [[ $# -ge 3 ]]; then
    DAYS2=$3
fi

archiveDir=$DIR/archive/`date +%Y_%m_%d_%H_%M`
mkdir -p $archiveDir

$findExec -P $DIR -type f -mtime +$DAYS2 -exec rm {} \;

for f in `$findExec -P $DIR -type f -mtime +$DAYS1 | $grepExec -vP "($DIR)archive/.*"`
do
    myDir=`dirname $f`/
    mkdir -p $archiveDir/${myDir#$DIR}
    mv $f $archiveDir/${myDir#$DIR}
done

$findExec -P $DIR/* -type d -empty -delete
